version: 2
updates:
- package-ecosystem: gradle
  directory: "/app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.bouncycastle:bcpkix-jdk15on
    versions:
    - "> 1.65"
